//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public Manufacturer()
        {
            this.RawMaterialManufacturers = new HashSet<RawMaterialManufacturer>();
            this.SupplierAssurances = new HashSet<SupplierAssurance>();
            this.SupplierQuestionnaires = new HashSet<SupplierQuestionnaire>();
        }
    
        public int ManufacturerID { get; set; }
        public Nullable<int> GlobalCompanyID { get; set; }
        public int SupplierID { get; set; }
        public string MSiteName { get; set; }
        public string MAddress1 { get; set; }
        public string MAddress2 { get; set; }
        public string MAddress3 { get; set; }
        public string MAddress4 { get; set; }
        public string MAddress5 { get; set; }
        public Nullable<int> MCountryID { get; set; }
        public string MPostCode { get; set; }
        public string MTel { get; set; }
        public string MFax { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MName { get; set; }
        public string MContactEmail { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<bool> Active { get; set; }
        public string RegistrationNo { get; set; }
        public string MSiteCode { get; set; }
        public Nullable<int> ClientID { get; set; }
    
        public virtual ICollection<RawMaterialManufacturer> RawMaterialManufacturers { get; set; }
        public virtual ICollection<SupplierAssurance> SupplierAssurances { get; set; }
        public virtual ICollection<SupplierQuestionnaire> SupplierQuestionnaires { get; set; }
    }
}
