//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HACCPNowSQLDevEntities : DbContext
    {
        public HACCPNowSQLDevEntities(string connectionstring)
            : base(connectionstring)

        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<RawMaterial> RawMaterials { get; set; }
        public DbSet<RawMaterialManufacturer> RawMaterialManufacturers { get; set; }
        public DbSet<RawMaterialSupplier> RawMaterialSuppliers { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<SupplierAssurance> SupplierAssurances { get; set; }
        public DbSet<SupplierDocument> SupplierDocuments { get; set; }
        public DbSet<SupplierQuestionnaire> SupplierQuestionnaires { get; set; }
    }
}
