//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialManufacturer
    {
        public int RawMaterialManufacturerID { get; set; }
        public Nullable<int> RawMaterialID { get; set; }
        public int ManufacturerID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsSelectedForSupplier { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
