//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterialSupplier
    {
        public int RawMaterialSupplierID { get; set; }
        public int RawMaterialID { get; set; }
        public int SupplierID { get; set; }
        public string RawMaterial { get; set; }
        public string Variety { get; set; }
        public string Brand { get; set; }
        public string PackSize { get; set; }
        public string Packaging { get; set; }
        public string LegalName { get; set; }
        public string RawMaterialDescription { get; set; }
        public string IngrDeclaration { get; set; }
        public string RawMaterialOrganicDescription { get; set; }
        public Nullable<int> RawMaterialShelfLifeID { get; set; }
        public string RawMaterialSAPCode { get; set; }
        public Nullable<decimal> RawMaterialUnitCost { get; set; }
        public string CommercialCode { get; set; }
        public Nullable<bool> IsReadyToEat { get; set; }
        public Nullable<bool> IsBulkProduct { get; set; }
        public string SupplierProductCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierFDARegNo { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerFDARegNo { get; set; }
        public string DateCodeFormat { get; set; }
        public string BatchLotCodeDetail { get; set; }
        public string ShelfLifeDesignation { get; set; }
        public string ShelfLifeUnopened { get; set; }
        public string ShelfLifeOpened { get; set; }
        public string DistributionChain { get; set; }
        public Nullable<int> FSVPExemptYesNoOnlyListID { get; set; }
        public Nullable<int> FSVPInPlaceYesNoListID { get; set; }
        public string FSVPDocumentName { get; set; }
        public string CountryOfOrigin { get; set; }
        public Nullable<int> CountryOfOriginID { get; set; }
        public string CountryOfTransit { get; set; }
        public Nullable<int> CountryOfTransitID { get; set; }
        public string CountryOfManufacture { get; set; }
        public Nullable<int> CountryOfManufactureID { get; set; }
        public Nullable<bool> IsAutoQuestionnaire { get; set; }
        public Nullable<int> QuestionnaireID { get; set; }
        public Nullable<int> SupplierQuestionnaireID { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> ApprovedUserID { get; set; }
        public string ApprovalBasis { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DocumentPath { get; set; }
        public byte[] RawMaterialDocument { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public string ServingsPerContainer { get; set; }
        public string ServingSize { get; set; }
        public Nullable<int> FSVPDocumentFileNameID { get; set; }
        public Nullable<int> RawMaterialTypeID { get; set; }
        public string GTIN { get; set; }
        public string MethodOfProduction { get; set; }
        public string SupplierRawMaterialName { get; set; }
        public Nullable<int> LinkedRawMaterialListID { get; set; }
        public Nullable<int> VatRateID { get; set; }
        public string LeadTime { get; set; }
        public string MakeUpInstruction { get; set; }
        public Nullable<decimal> MaterialUnitNetWtKg { get; set; }
        public Nullable<decimal> PlasticTaxGramsPerKg { get; set; }
    
        public virtual RawMaterial RawMaterial1 { get; set; }
        public virtual RawMaterial RawMaterial2 { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
