//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.RawMaterialManufacturers = new HashSet<RawMaterialManufacturer>();
            this.RawMaterialSuppliers = new HashSet<RawMaterialSupplier>();
            this.SupplierAssurances = new HashSet<SupplierAssurance>();
            this.SupplierDocuments = new HashSet<SupplierDocument>();
            this.SupplierQuestionnaires = new HashSet<SupplierQuestionnaire>();
        }
    
        public int SupplierID { get; set; }
        public string Supplier1 { get; set; }
        public string SupplierRef { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
        public Nullable<int> SupplierGroupID { get; set; }
        public string SiteName { get; set; }
        public bool AddressOptional { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string PostCode { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string WebSiteURL { get; set; }
        public string MSiteName { get; set; }
        public string MAddress1 { get; set; }
        public string MAddress2 { get; set; }
        public string MAddress3 { get; set; }
        public string MAddress4 { get; set; }
        public string MAddress5 { get; set; }
        public Nullable<int> MCountryID { get; set; }
        public string MPostCode { get; set; }
        public string MTel { get; set; }
        public string MFax { get; set; }
        public string CompanyProfile { get; set; }
        public string MainContact { get; set; }
        public string MainContactJobTitle { get; set; }
        public string MainContactEmail { get; set; }
        public string MainContactTel { get; set; }
        public string TechContact { get; set; }
        public string TechContactJobTitle { get; set; }
        public string TechContactEmail { get; set; }
        public string TechContactTel { get; set; }
        public string TechContactPassword { get; set; }
        public Nullable<bool> SendChaserEmails { get; set; }
        public Nullable<int> AccountManagerUserID { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactJobTitle { get; set; }
        public string EmergencyContactEmail { get; set; }
        public string EmergencyContactTel { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> AutoQuestionnaire { get; set; }
        public Nullable<int> MonitoringFormID { get; set; }
        public string SedexNo { get; set; }
        public Nullable<bool> IsSMETAAudit { get; set; }
        public string SMETAPillar { get; set; }
        public string HealthMarkNo { get; set; }
        public string LiabilityPerOccurence { get; set; }
        public string LiabilityPersonalInjury { get; set; }
        public string LiabilityGeneralAggregate { get; set; }
        public string LiabilityProductsAggregate { get; set; }
        public string LiabilityAuto { get; set; }
        public string LiabilityMotorTruck { get; set; }
        public string LiabilityExcessUmbrella { get; set; }
        public string LiabilityEmployers { get; set; }
        public bool StatutoryWorkersCompensation { get; set; }
        public bool CertifyAdditionalInsured { get; set; }
        public string Turnover { get; set; }
        public string ManufacturingCapacity { get; set; }
        public Nullable<int> NoFTEmployees { get; set; }
        public Nullable<int> NoPTEmployees { get; set; }
        public string PremisesSize { get; set; }
        public Nullable<int> YearOfConstruction { get; set; }
        public Nullable<int> YearEstablished { get; set; }
        public string NameOfParentCo { get; set; }
        public string NoProductsManufactured { get; set; }
        public string NoExportShipmentsPerYear { get; set; }
        public string AnnualExportValue { get; set; }
        public string DescriptionOfProducts { get; set; }
        public Nullable<int> IsGFSICertificatedYesNoOnlyListID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public bool Active { get; set; }
        public string ImportID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<bool> IsCCToCommerial { get; set; }
        public string DunsNo { get; set; }
        public Nullable<bool> IsOptional { get; set; }
        public string GFBIHashID { get; set; }
        public Nullable<bool> InDevelopment { get; set; }
        public Nullable<bool> IsGlobal { get; set; }
        public Nullable<int> ApprovalStatusID { get; set; }
        public Nullable<int> GlobalSupplierID { get; set; }
        public bool IsSeparateRemittance { get; set; }
        public string RemitAddress1 { get; set; }
        public string RemitAddress2 { get; set; }
        public string RemitAddress3 { get; set; }
        public string RemitAddress4 { get; set; }
        public string RemitAddress5 { get; set; }
        public Nullable<int> RemitCountryID { get; set; }
        public string RemitPostCode { get; set; }
        public string AccountsContactName { get; set; }
        public string AccountsTitle { get; set; }
        public string AccountsEmail { get; set; }
        public string AccountsFax { get; set; }
        public string AccountsTel { get; set; }
        public string FoodSafetyContactName { get; set; }
        public string FoodSafetyTitle { get; set; }
        public string FoodSafetyEMail { get; set; }
        public string FoodSafetyAltEmail { get; set; }
        public string FoodSafetyTel { get; set; }
        public string DocumentationURL { get; set; }
        public bool IsFoodSafetyTheRecallContact { get; set; }
        public string RecallContactName { get; set; }
        public string RecallTitle { get; set; }
        public string RecallEmail { get; set; }
        public string RecallOfficeNo { get; set; }
        public string RecallMobileNo { get; set; }
        public string RecallFaxNo { get; set; }
        public string USDARegNo { get; set; }
        public bool IsFDARegistered { get; set; }
        public Nullable<System.DateTime> FDARegDate { get; set; }
        public string FDARegNo { get; set; }
        public string USAgentName { get; set; }
        public string USAgentAddress { get; set; }
        public string USTarriffNo { get; set; }
        public string TaxIDNo { get; set; }
        public string PACARegNo { get; set; }
        public string DRCRegNo { get; set; }
        public bool IsUSDARegistered { get; set; }
        public string SupplierSapCode { get; set; }
        public string SupplierPassword { get; set; }
        public string SupplierPasswordSalt { get; set; }
        public string FDALoginUserID { get; set; }
        public string FDALoginPassword { get; set; }
        public string FDALoginPIN { get; set; }
        public string GPSCoordinates { get; set; }
        public string OtherCertification { get; set; }
        public string ProductClaims { get; set; }
        public string InsurerName { get; set; }
        public string PolicyNo { get; set; }
        public string ShiftPatterns { get; set; }
        public Nullable<int> IsOnSiteStorageYesNoOnlyListID { get; set; }
        public Nullable<int> IsOffsiteStorageYesNoOnlyListID { get; set; }
        public string DistributionDescription { get; set; }
        public Nullable<int> NoTempEmployees { get; set; }
        public Nullable<int> NoEngEmployees { get; set; }
        public Nullable<int> NoQualEmployees { get; set; }
        public Nullable<int> NoTechEmployees { get; set; }
    
        public virtual ICollection<RawMaterialManufacturer> RawMaterialManufacturers { get; set; }
        public virtual ICollection<RawMaterialSupplier> RawMaterialSuppliers { get; set; }
        public virtual ICollection<SupplierAssurance> SupplierAssurances { get; set; }
        public virtual ICollection<SupplierDocument> SupplierDocuments { get; set; }
        public virtual ICollection<SupplierQuestionnaire> SupplierQuestionnaires { get; set; }
    }
}
