//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitecture.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierQuestionnaire
    {
        public int SupplierQuestionnaireID { get; set; }
        public int QuestionnaireID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> RawMaterialID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> DateSupplierSent { get; set; }
        public Nullable<System.DateTime> DateSupplierReceived { get; set; }
        public Nullable<System.DateTime> DateSupplierApproved { get; set; }
        public bool SubmittedForApproval { get; set; }
        public System.DateTime SubmittedForApprovalDate { get; set; }
        public Nullable<System.DateTime> QuestionnaireDeadline { get; set; }
        public bool FeedbackRequired { get; set; }
        public Nullable<bool> AgreeElectronicSign { get; set; }
        public Nullable<bool> AgreeNoDeviation { get; set; }
        public Nullable<bool> AccurateStatementOfFact { get; set; }
        public Nullable<bool> AuthorisedToSign { get; set; }
        public Nullable<bool> DocumentUsedAsEvidence { get; set; }
        public Nullable<bool> FDACompliance { get; set; }
        public Nullable<bool> UKEUStatutoryRequirement { get; set; }
        public Nullable<bool> TrueRepresentationOfProduct { get; set; }
        public Nullable<bool> ChangesMustBeNotified { get; set; }
        public Nullable<bool> RecordsHeld1Year { get; set; }
        public Nullable<bool> IncidentNotifications { get; set; }
        public Nullable<bool> RecallNotifications { get; set; }
        public Nullable<bool> WithdrawalNotifications { get; set; }
        public string SupplierSignName { get; set; }
        public string SupplierSignPosition { get; set; }
        public string SupplierSignCompany { get; set; }
        public Nullable<System.DateTime> SupplierSignDate { get; set; }
        public string CustomerSignName { get; set; }
        public string CustomerSignPosition { get; set; }
        public string CustomerSignCompany { get; set; }
        public Nullable<System.DateTime> CustomerSignDate { get; set; }
        public string SupplierApprovedBy { get; set; }
        public string SupplierApprovedTtitle { get; set; }
        public string CustomerApprovedBy { get; set; }
        public string CustomerAprovedTitle { get; set; }
        public string LatestIssueNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string DocumentRef { get; set; }
        public byte[] FinalPDF { get; set; }
        public string FinalPDFURL { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> TransferToMfg { get; set; }
        public string SignInToken { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string ApprovalCode { get; set; }
        public Nullable<int> AuditRatingID { get; set; }
        public Nullable<bool> InDevelopment { get; set; }
        public Nullable<int> UpdatedByUserID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> DefaultAccountManagerID { get; set; }
        public string AzureStorageURL { get; set; }
        public string SupplierSignDigitalSignature { get; set; }
        public string CustomerSignDigitalSignature { get; set; }
        public string AgentSignDigitalSignature { get; set; }
        public Nullable<bool> IsFromWebsite { get; set; }
        public string NutshellLeadID { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual RawMaterial RawMaterial { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
